server:
  port: 10005
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
  profiles:
    active: dev


# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chatroom.entity