server:
  port: 10005
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chatroom?useUnicode=true&characterEncoding=utf-8