server:
  port: 10005
spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  data:
    mongodb:
      uri: mongodb://192.168.0.110:27017/opsigte

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chatroom.entity

# mongodb配置