server:
  port: 10005
spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  data:
    # mongodb配置
    mongodb:
      uri: mongodb://192.168.0.110:27017/chatroom
      #uri: mongodb://192.168.1.110:27017/chatroom
      #uri: mongodb://47.89.188.196:27017/chatroom

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chatroom.entity

